project:
  type: website
  output-dir: docs

website:
  title: "Sebastian Suarez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: https://github.com/sebastiansuarez189/myrepo.git  
        text: Github
      - href: Code.qmd
        text: Research Code
      - href: analysis.qmd
        text: Statistical Analysis
      - href: Homer's Web Site.qmd
        text: Best Website

        
      
        
      

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

