project:
  type: website
  output-dir: docs

website:
  title: "sebastiansuarez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: https://github.com/sebastiansuarez189/myrepo.git  
        text: Research2
      
        
      

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

